/********************************************************************************
** Form generated from reading UI file 'PDFDocument.ui'
**
** Created: Sat Apr 6 13:26:39 2013
**      by: Qt User Interface Compiler version 4.8.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PDFDOCUMENT_H
#define UI_PDFDOCUMENT_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QStatusBar>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_PDFDocument
{
public:
    QAction *actionAbout_TW;
    QAction *actionFirst_Page;
    QAction *actionPrevious_Page;
    QAction *actionNext_Page;
    QAction *actionLast_Page;
    QAction *actionGo_to_Page;
    QAction *actionZoom_In;
    QAction *actionZoom_Out;
    QAction *actionFit_to_Window;
    QAction *actionActual_Size;
    QAction *actionFit_to_Width;
    QAction *actionNew;
    QAction *actionOpen;
    QAction *actionOpen_Recent;
    QAction *actionClose;
    QAction *actionUndo;
    QAction *actionRedo;
    QAction *actionCut;
    QAction *actionCopy;
    QAction *actionPaste;
    QAction *actionClear;
    QAction *actionTypeset;
    QAction *actionExternalViewer;
    QAction *actionPreferences;
    QAction *actionStack;
    QAction *actionTile;
    QAction *actionGo_to_Source;
    QAction *actionNew_from_Template;
    QAction *actionFull_Screen;
    QAction *actionMagnify;
    QAction *actionScroll;
    QAction *actionSelect_Text;
    QAction *actionSelect_Image;
    QAction *actionUserManual;
    QAction *actionWriteToMailingList;
    QAction *actionSide_by_Side;
    QAction *actionPlace_on_Left;
    QAction *actionPlace_on_Right;
    QAction *actionQuit_TeXworks;
    QAction *actionFind;
    QAction *actionFind_Again;
    QAction *actionUpdate_Scripts;
    QAction *actionManage_Scripts;
    QAction *actionShow_Scripts_Folder;
    QAction *actionAbout_Scripts;
    QAction *actionS;
    QAction *actionCloseSomething;
    QAction *actionScrolling_follows_cursor;
    QAction *actionCursor_follows_scrolling;
    QAction *actionFind_2;
    QAction *actionFind_again;
    QAction *actionNew_Window;
    QAction *actionGrid11;
    QAction *actionGrid21;
    QAction *actionGrid12;
    QAction *actionGrid22;
    QAction *actionGrid23;
    QAction *actionGrid33;
    QAction *actionCustom;
    QAction *actionSinglePageStep;
    QAction *actionSynchronize_multiple_views;
    QAction *actionPresentation;
    QAction *actionContinuous;
    QAction *action_Print;
    QAction *actionFileOpen;
    QAction *actionBack;
    QAction *actionForward;
    QAction *actionToggleEmbedded;
    QWidget *centralwidget;
    QMenuBar *menubar;
    QMenu *menuHelp;
    QMenu *menuFile;
    QMenu *menuEdit;
    QMenu *menuView;
    QMenu *menuGrid;
    QMenu *menuWindow;
    QMenu *menuShow;
    QMenu *menuEdit_2;
    QStatusBar *statusbar;
    QToolBar *toolBar;

    void setupUi(QMainWindow *PDFDocument)
    {
        if (PDFDocument->objectName().isEmpty())
            PDFDocument->setObjectName(QString::fromUtf8("PDFDocument"));
        PDFDocument->resize(1197, 600);
        PDFDocument->setAcceptDrops(true);
        actionAbout_TW = new QAction(PDFDocument);
        actionAbout_TW->setObjectName(QString::fromUtf8("actionAbout_TW"));
        actionAbout_TW->setMenuRole(QAction::AboutRole);
        actionFirst_Page = new QAction(PDFDocument);
        actionFirst_Page->setObjectName(QString::fromUtf8("actionFirst_Page"));
        actionFirst_Page->setShortcut(QString::fromUtf8("Home"));
        actionFirst_Page->setMenuRole(QAction::NoRole);
        actionPrevious_Page = new QAction(PDFDocument);
        actionPrevious_Page->setObjectName(QString::fromUtf8("actionPrevious_Page"));
        actionPrevious_Page->setShortcut(QString::fromUtf8("Ctrl+PgUp"));
        actionPrevious_Page->setMenuRole(QAction::NoRole);
        actionNext_Page = new QAction(PDFDocument);
        actionNext_Page->setObjectName(QString::fromUtf8("actionNext_Page"));
        actionNext_Page->setShortcut(QString::fromUtf8("Ctrl+PgDown"));
        actionNext_Page->setMenuRole(QAction::NoRole);
        actionLast_Page = new QAction(PDFDocument);
        actionLast_Page->setObjectName(QString::fromUtf8("actionLast_Page"));
        actionLast_Page->setShortcut(QString::fromUtf8("End"));
        actionLast_Page->setMenuRole(QAction::NoRole);
        actionGo_to_Page = new QAction(PDFDocument);
        actionGo_to_Page->setObjectName(QString::fromUtf8("actionGo_to_Page"));
        actionGo_to_Page->setMenuRole(QAction::NoRole);
        actionZoom_In = new QAction(PDFDocument);
        actionZoom_In->setObjectName(QString::fromUtf8("actionZoom_In"));
        actionZoom_In->setMenuRole(QAction::NoRole);
        actionZoom_Out = new QAction(PDFDocument);
        actionZoom_Out->setObjectName(QString::fromUtf8("actionZoom_Out"));
        actionZoom_Out->setMenuRole(QAction::NoRole);
        actionFit_to_Window = new QAction(PDFDocument);
        actionFit_to_Window->setObjectName(QString::fromUtf8("actionFit_to_Window"));
        actionFit_to_Window->setCheckable(true);
        actionFit_to_Window->setMenuRole(QAction::NoRole);
        actionActual_Size = new QAction(PDFDocument);
        actionActual_Size->setObjectName(QString::fromUtf8("actionActual_Size"));
        actionActual_Size->setMenuRole(QAction::NoRole);
        actionFit_to_Width = new QAction(PDFDocument);
        actionFit_to_Width->setObjectName(QString::fromUtf8("actionFit_to_Width"));
        actionFit_to_Width->setCheckable(true);
        actionFit_to_Width->setMenuRole(QAction::NoRole);
        actionNew = new QAction(PDFDocument);
        actionNew->setObjectName(QString::fromUtf8("actionNew"));
        actionNew->setMenuRole(QAction::NoRole);
        actionOpen = new QAction(PDFDocument);
        actionOpen->setObjectName(QString::fromUtf8("actionOpen"));
        actionOpen->setMenuRole(QAction::NoRole);
        actionOpen_Recent = new QAction(PDFDocument);
        actionOpen_Recent->setObjectName(QString::fromUtf8("actionOpen_Recent"));
        actionOpen_Recent->setMenuRole(QAction::NoRole);
        actionClose = new QAction(PDFDocument);
        actionClose->setObjectName(QString::fromUtf8("actionClose"));
        actionClose->setMenuRole(QAction::NoRole);
        actionUndo = new QAction(PDFDocument);
        actionUndo->setObjectName(QString::fromUtf8("actionUndo"));
        actionUndo->setEnabled(false);
        actionUndo->setMenuRole(QAction::NoRole);
        actionRedo = new QAction(PDFDocument);
        actionRedo->setObjectName(QString::fromUtf8("actionRedo"));
        actionRedo->setEnabled(false);
        actionRedo->setMenuRole(QAction::NoRole);
        actionCut = new QAction(PDFDocument);
        actionCut->setObjectName(QString::fromUtf8("actionCut"));
        actionCut->setEnabled(false);
        actionCut->setMenuRole(QAction::NoRole);
        actionCopy = new QAction(PDFDocument);
        actionCopy->setObjectName(QString::fromUtf8("actionCopy"));
        actionCopy->setEnabled(false);
        actionCopy->setMenuRole(QAction::NoRole);
        actionPaste = new QAction(PDFDocument);
        actionPaste->setObjectName(QString::fromUtf8("actionPaste"));
        actionPaste->setEnabled(false);
        actionPaste->setMenuRole(QAction::NoRole);
        actionClear = new QAction(PDFDocument);
        actionClear->setObjectName(QString::fromUtf8("actionClear"));
        actionClear->setEnabled(false);
        actionClear->setMenuRole(QAction::NoRole);
        actionTypeset = new QAction(PDFDocument);
        actionTypeset->setObjectName(QString::fromUtf8("actionTypeset"));
        actionTypeset->setMenuRole(QAction::NoRole);
        actionExternalViewer = new QAction(PDFDocument);
        actionExternalViewer->setObjectName(QString::fromUtf8("actionExternalViewer"));
        actionExternalViewer->setMenuRole(QAction::NoRole);
        actionPreferences = new QAction(PDFDocument);
        actionPreferences->setObjectName(QString::fromUtf8("actionPreferences"));
        actionPreferences->setMenuRole(QAction::PreferencesRole);
        actionStack = new QAction(PDFDocument);
        actionStack->setObjectName(QString::fromUtf8("actionStack"));
        actionStack->setMenuRole(QAction::NoRole);
        actionTile = new QAction(PDFDocument);
        actionTile->setObjectName(QString::fromUtf8("actionTile"));
        actionTile->setMenuRole(QAction::NoRole);
        actionGo_to_Source = new QAction(PDFDocument);
        actionGo_to_Source->setObjectName(QString::fromUtf8("actionGo_to_Source"));
        actionGo_to_Source->setEnabled(true);
        actionGo_to_Source->setMenuRole(QAction::NoRole);
        actionNew_from_Template = new QAction(PDFDocument);
        actionNew_from_Template->setObjectName(QString::fromUtf8("actionNew_from_Template"));
        actionNew_from_Template->setMenuRole(QAction::NoRole);
        actionFull_Screen = new QAction(PDFDocument);
        actionFull_Screen->setObjectName(QString::fromUtf8("actionFull_Screen"));
        actionFull_Screen->setCheckable(true);
        actionFull_Screen->setMenuRole(QAction::NoRole);
        actionMagnify = new QAction(PDFDocument);
        actionMagnify->setObjectName(QString::fromUtf8("actionMagnify"));
        actionMagnify->setCheckable(true);
        actionMagnify->setChecked(true);
        actionScroll = new QAction(PDFDocument);
        actionScroll->setObjectName(QString::fromUtf8("actionScroll"));
        actionScroll->setCheckable(true);
        actionSelect_Text = new QAction(PDFDocument);
        actionSelect_Text->setObjectName(QString::fromUtf8("actionSelect_Text"));
        actionSelect_Text->setCheckable(true);
        actionSelect_Image = new QAction(PDFDocument);
        actionSelect_Image->setObjectName(QString::fromUtf8("actionSelect_Image"));
        actionSelect_Image->setCheckable(true);
        actionUserManual = new QAction(PDFDocument);
        actionUserManual->setObjectName(QString::fromUtf8("actionUserManual"));
        actionWriteToMailingList = new QAction(PDFDocument);
        actionWriteToMailingList->setObjectName(QString::fromUtf8("actionWriteToMailingList"));
        actionSide_by_Side = new QAction(PDFDocument);
        actionSide_by_Side->setObjectName(QString::fromUtf8("actionSide_by_Side"));
        actionSide_by_Side->setEnabled(true);
        actionPlace_on_Left = new QAction(PDFDocument);
        actionPlace_on_Left->setObjectName(QString::fromUtf8("actionPlace_on_Left"));
        actionPlace_on_Right = new QAction(PDFDocument);
        actionPlace_on_Right->setObjectName(QString::fromUtf8("actionPlace_on_Right"));
        actionQuit_TeXworks = new QAction(PDFDocument);
        actionQuit_TeXworks->setObjectName(QString::fromUtf8("actionQuit_TeXworks"));
        actionQuit_TeXworks->setMenuRole(QAction::QuitRole);
        actionFind = new QAction(PDFDocument);
        actionFind->setObjectName(QString::fromUtf8("actionFind"));
        actionFind->setShortcutContext(Qt::WindowShortcut);
        actionFind->setMenuRole(QAction::NoRole);
        actionFind_Again = new QAction(PDFDocument);
        actionFind_Again->setObjectName(QString::fromUtf8("actionFind_Again"));
        actionFind_Again->setShortcutContext(Qt::WindowShortcut);
        actionFind_Again->setMenuRole(QAction::NoRole);
        actionUpdate_Scripts = new QAction(PDFDocument);
        actionUpdate_Scripts->setObjectName(QString::fromUtf8("actionUpdate_Scripts"));
        actionUpdate_Scripts->setMenuRole(QAction::NoRole);
        actionManage_Scripts = new QAction(PDFDocument);
        actionManage_Scripts->setObjectName(QString::fromUtf8("actionManage_Scripts"));
        actionManage_Scripts->setMenuRole(QAction::NoRole);
        actionShow_Scripts_Folder = new QAction(PDFDocument);
        actionShow_Scripts_Folder->setObjectName(QString::fromUtf8("actionShow_Scripts_Folder"));
        actionShow_Scripts_Folder->setMenuRole(QAction::NoRole);
        actionAbout_Scripts = new QAction(PDFDocument);
        actionAbout_Scripts->setObjectName(QString::fromUtf8("actionAbout_Scripts"));
        actionAbout_Scripts->setMenuRole(QAction::NoRole);
        actionS = new QAction(PDFDocument);
        actionS->setObjectName(QString::fromUtf8("actionS"));
        actionCloseSomething = new QAction(PDFDocument);
        actionCloseSomething->setObjectName(QString::fromUtf8("actionCloseSomething"));
        actionScrolling_follows_cursor = new QAction(PDFDocument);
        actionScrolling_follows_cursor->setObjectName(QString::fromUtf8("actionScrolling_follows_cursor"));
        actionScrolling_follows_cursor->setCheckable(true);
        actionCursor_follows_scrolling = new QAction(PDFDocument);
        actionCursor_follows_scrolling->setObjectName(QString::fromUtf8("actionCursor_follows_scrolling"));
        actionCursor_follows_scrolling->setCheckable(true);
        actionFind_2 = new QAction(PDFDocument);
        actionFind_2->setObjectName(QString::fromUtf8("actionFind_2"));
        actionFind_again = new QAction(PDFDocument);
        actionFind_again->setObjectName(QString::fromUtf8("actionFind_again"));
        actionNew_Window = new QAction(PDFDocument);
        actionNew_Window->setObjectName(QString::fromUtf8("actionNew_Window"));
        actionGrid11 = new QAction(PDFDocument);
        actionGrid11->setObjectName(QString::fromUtf8("actionGrid11"));
        actionGrid11->setProperty("grid", QVariant(QString::fromUtf8("1x1")));
        actionGrid21 = new QAction(PDFDocument);
        actionGrid21->setObjectName(QString::fromUtf8("actionGrid21"));
        actionGrid21->setProperty("grid", QVariant(QString::fromUtf8("2x1")));
        actionGrid12 = new QAction(PDFDocument);
        actionGrid12->setObjectName(QString::fromUtf8("actionGrid12"));
        actionGrid12->setProperty("grid", QVariant(QString::fromUtf8("1x2")));
        actionGrid22 = new QAction(PDFDocument);
        actionGrid22->setObjectName(QString::fromUtf8("actionGrid22"));
        actionGrid22->setProperty("grid", QVariant(QString::fromUtf8("2x2")));
        actionGrid23 = new QAction(PDFDocument);
        actionGrid23->setObjectName(QString::fromUtf8("actionGrid23"));
        actionGrid23->setProperty("grid", QVariant(QString::fromUtf8("23")));
        actionGrid33 = new QAction(PDFDocument);
        actionGrid33->setObjectName(QString::fromUtf8("actionGrid33"));
        actionGrid33->setProperty("grid", QVariant(QString::fromUtf8("33")));
        actionCustom = new QAction(PDFDocument);
        actionCustom->setObjectName(QString::fromUtf8("actionCustom"));
        actionCustom->setProperty("grid", QVariant(QString::fromUtf8("xx")));
        actionSinglePageStep = new QAction(PDFDocument);
        actionSinglePageStep->setObjectName(QString::fromUtf8("actionSinglePageStep"));
        actionSinglePageStep->setCheckable(true);
        actionSinglePageStep->setChecked(false);
        actionSynchronize_multiple_views = new QAction(PDFDocument);
        actionSynchronize_multiple_views->setObjectName(QString::fromUtf8("actionSynchronize_multiple_views"));
        actionSynchronize_multiple_views->setCheckable(true);
        actionSynchronize_multiple_views->setChecked(true);
        actionPresentation = new QAction(PDFDocument);
        actionPresentation->setObjectName(QString::fromUtf8("actionPresentation"));
        actionPresentation->setCheckable(true);
        actionContinuous = new QAction(PDFDocument);
        actionContinuous->setObjectName(QString::fromUtf8("actionContinuous"));
        actionContinuous->setCheckable(true);
        actionContinuous->setChecked(true);
        action_Print = new QAction(PDFDocument);
        action_Print->setObjectName(QString::fromUtf8("action_Print"));
        actionFileOpen = new QAction(PDFDocument);
        actionFileOpen->setObjectName(QString::fromUtf8("actionFileOpen"));
        actionBack = new QAction(PDFDocument);
        actionBack->setObjectName(QString::fromUtf8("actionBack"));
        actionForward = new QAction(PDFDocument);
        actionForward->setObjectName(QString::fromUtf8("actionForward"));
        actionToggleEmbedded = new QAction(PDFDocument);
        actionToggleEmbedded->setObjectName(QString::fromUtf8("actionToggleEmbedded"));
        centralwidget = new QWidget(PDFDocument);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        PDFDocument->setCentralWidget(centralwidget);
        menubar = new QMenuBar(PDFDocument);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1197, 21));
        menuHelp = new QMenu(menubar);
        menuHelp->setObjectName(QString::fromUtf8("menuHelp"));
        menuFile = new QMenu(menubar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        menuEdit = new QMenu(menubar);
        menuEdit->setObjectName(QString::fromUtf8("menuEdit"));
        menuView = new QMenu(menubar);
        menuView->setObjectName(QString::fromUtf8("menuView"));
        menuGrid = new QMenu(menuView);
        menuGrid->setObjectName(QString::fromUtf8("menuGrid"));
        menuWindow = new QMenu(menubar);
        menuWindow->setObjectName(QString::fromUtf8("menuWindow"));
        menuShow = new QMenu(menuWindow);
        menuShow->setObjectName(QString::fromUtf8("menuShow"));
        menuEdit_2 = new QMenu(menubar);
        menuEdit_2->setObjectName(QString::fromUtf8("menuEdit_2"));
        PDFDocument->setMenuBar(menubar);
        statusbar = new QStatusBar(PDFDocument);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        QFont font;
        font.setPointSize(10);
        statusbar->setFont(font);
        PDFDocument->setStatusBar(statusbar);
        toolBar = new QToolBar(PDFDocument);
        toolBar->setObjectName(QString::fromUtf8("toolBar"));
        toolBar->setIconSize(QSize(24, 24));
        PDFDocument->addToolBar(Qt::TopToolBarArea, toolBar);

        menubar->addAction(menuFile->menuAction());
        menubar->addAction(menuEdit_2->menuAction());
        menubar->addAction(menuView->menuAction());
        menubar->addAction(menuWindow->menuAction());
        menubar->addAction(menuEdit->menuAction());
        menubar->addAction(menuHelp->menuAction());
        menuHelp->addAction(actionUserManual);
        menuHelp->addSeparator();
        menuHelp->addAction(actionAbout_TW);
        menuFile->addAction(actionFileOpen);
        menuFile->addAction(action_Print);
        menuFile->addAction(actionClose);
        menuFile->addSeparator();
        menuFile->addAction(actionQuit_TeXworks);
        menuEdit->addAction(actionPreferences);
        menuEdit->addSeparator();
        menuEdit->addAction(actionScrolling_follows_cursor);
        menuEdit->addAction(actionCursor_follows_scrolling);
        menuEdit->addAction(actionSynchronize_multiple_views);
        menuView->addAction(actionFirst_Page);
        menuView->addAction(actionBack);
        menuView->addAction(actionPrevious_Page);
        menuView->addAction(actionNext_Page);
        menuView->addAction(actionForward);
        menuView->addAction(actionLast_Page);
        menuView->addSeparator();
        menuView->addAction(actionGo_to_Page);
        menuView->addSeparator();
        menuView->addAction(actionZoom_In);
        menuView->addAction(actionZoom_Out);
        menuView->addAction(actionActual_Size);
        menuView->addAction(actionFit_to_Width);
        menuView->addAction(actionFit_to_Window);
        menuView->addAction(actionContinuous);
        menuView->addAction(menuGrid->menuAction());
        menuView->addSeparator();
        menuView->addAction(actionFull_Screen);
        menuView->addAction(actionPresentation);
        menuGrid->addAction(actionGrid11);
        menuGrid->addAction(actionGrid21);
        menuGrid->addAction(actionGrid12);
        menuGrid->addAction(actionGrid22);
        menuGrid->addAction(actionCustom);
        menuGrid->addSeparator();
        menuGrid->addAction(actionSinglePageStep);
        menuWindow->addAction(menuShow->menuAction());
        menuWindow->addAction(actionCloseSomething);
        menuWindow->addSeparator();
        menuWindow->addAction(actionStack);
        menuWindow->addAction(actionTile);
        menuWindow->addAction(actionSide_by_Side);
        menuWindow->addSeparator();
        menuWindow->addAction(actionGo_to_Source);
        menuWindow->addSeparator();
        menuWindow->addAction(actionNew_Window);
        menuEdit_2->addAction(actionFind_2);
        menuEdit_2->addAction(actionFind_again);
        toolBar->addAction(actionTypeset);
        toolBar->addSeparator();
        toolBar->addAction(actionToggleEmbedded);
        toolBar->addAction(actionExternalViewer);
        toolBar->addSeparator();
        toolBar->addAction(actionMagnify);
        toolBar->addAction(actionScroll);
        toolBar->addSeparator();
        toolBar->addAction(actionBack);
        toolBar->addAction(actionForward);
        toolBar->addSeparator();
        toolBar->addAction(actionFirst_Page);
        toolBar->addAction(actionPrevious_Page);
        toolBar->addAction(actionNext_Page);
        toolBar->addAction(actionLast_Page);
        toolBar->addSeparator();
        toolBar->addAction(actionActual_Size);
        toolBar->addAction(actionFit_to_Width);
        toolBar->addAction(actionFit_to_Window);
        toolBar->addSeparator();
        toolBar->addAction(actionClose);

        retranslateUi(PDFDocument);
        QObject::connect(actionClose, SIGNAL(triggered()), PDFDocument, SLOT(close()));

        QMetaObject::connectSlotsByName(PDFDocument);
    } // setupUi

    void retranslateUi(QMainWindow *PDFDocument)
    {
        PDFDocument->setWindowTitle(QApplication::translate("PDFDocument", "untitled.pdf[*]", 0, QApplication::UnicodeUTF8));
        actionAbout_TW->setText(QApplication::translate("PDFDocument", "&About TeXstudio...", 0, QApplication::UnicodeUTF8));
        actionFirst_Page->setText(QApplication::translate("PDFDocument", "&First Page", 0, QApplication::UnicodeUTF8));
        actionPrevious_Page->setText(QApplication::translate("PDFDocument", "&Previous Page", 0, QApplication::UnicodeUTF8));
        actionNext_Page->setText(QApplication::translate("PDFDocument", "&Next Page", 0, QApplication::UnicodeUTF8));
        actionLast_Page->setText(QApplication::translate("PDFDocument", "&Last Page", 0, QApplication::UnicodeUTF8));
        actionGo_to_Page->setText(QApplication::translate("PDFDocument", "&Go to Page...", 0, QApplication::UnicodeUTF8));
        actionGo_to_Page->setShortcut(QApplication::translate("PDFDocument", "Ctrl+J", 0, QApplication::UnicodeUTF8));
        actionZoom_In->setText(QApplication::translate("PDFDocument", "Zoom &In", 0, QApplication::UnicodeUTF8));
        actionZoom_In->setShortcut(QApplication::translate("PDFDocument", "Ctrl++", 0, QApplication::UnicodeUTF8));
        actionZoom_Out->setText(QApplication::translate("PDFDocument", "Zoom &Out", 0, QApplication::UnicodeUTF8));
        actionZoom_Out->setShortcut(QApplication::translate("PDFDocument", "Ctrl+-", 0, QApplication::UnicodeUTF8));
        actionFit_to_Window->setText(QApplication::translate("PDFDocument", "Fit to &Window", 0, QApplication::UnicodeUTF8));
        actionFit_to_Window->setShortcut(QApplication::translate("PDFDocument", "Ctrl+3", 0, QApplication::UnicodeUTF8));
        actionActual_Size->setText(QApplication::translate("PDFDocument", "&Actual Size", 0, QApplication::UnicodeUTF8));
        actionActual_Size->setShortcut(QApplication::translate("PDFDocument", "Ctrl+1", 0, QApplication::UnicodeUTF8));
        actionFit_to_Width->setText(QApplication::translate("PDFDocument", "Fit to Wi&dth", 0, QApplication::UnicodeUTF8));
        actionFit_to_Width->setShortcut(QApplication::translate("PDFDocument", "Ctrl+2", 0, QApplication::UnicodeUTF8));
        actionNew->setText(QApplication::translate("PDFDocument", "New", 0, QApplication::UnicodeUTF8));
        actionNew->setShortcut(QApplication::translate("PDFDocument", "Ctrl+N", 0, QApplication::UnicodeUTF8));
        actionOpen->setText(QApplication::translate("PDFDocument", "Open...", 0, QApplication::UnicodeUTF8));
        actionOpen->setShortcut(QApplication::translate("PDFDocument", "Ctrl+O", 0, QApplication::UnicodeUTF8));
        actionOpen_Recent->setText(QApplication::translate("PDFDocument", "Open Recent", 0, QApplication::UnicodeUTF8));
        actionClose->setText(QApplication::translate("PDFDocument", "&Close", 0, QApplication::UnicodeUTF8));
        actionClose->setShortcut(QApplication::translate("PDFDocument", "Ctrl+W", 0, QApplication::UnicodeUTF8));
        actionUndo->setText(QApplication::translate("PDFDocument", "&Undo", 0, QApplication::UnicodeUTF8));
        actionUndo->setShortcut(QApplication::translate("PDFDocument", "Ctrl+Z", 0, QApplication::UnicodeUTF8));
        actionRedo->setText(QApplication::translate("PDFDocument", "&Redo", 0, QApplication::UnicodeUTF8));
        actionRedo->setShortcut(QApplication::translate("PDFDocument", "Ctrl+Shift+Z", 0, QApplication::UnicodeUTF8));
        actionCut->setText(QApplication::translate("PDFDocument", "C&ut", 0, QApplication::UnicodeUTF8));
        actionCut->setShortcut(QApplication::translate("PDFDocument", "Ctrl+X", 0, QApplication::UnicodeUTF8));
        actionCopy->setText(QApplication::translate("PDFDocument", "&Copy", 0, QApplication::UnicodeUTF8));
        actionCopy->setShortcut(QApplication::translate("PDFDocument", "Ctrl+C", 0, QApplication::UnicodeUTF8));
        actionPaste->setText(QApplication::translate("PDFDocument", "&Paste", 0, QApplication::UnicodeUTF8));
        actionPaste->setShortcut(QApplication::translate("PDFDocument", "Ctrl+V", 0, QApplication::UnicodeUTF8));
        actionClear->setText(QApplication::translate("PDFDocument", "C&lear", 0, QApplication::UnicodeUTF8));
        actionClear->setShortcut(QApplication::translate("PDFDocument", "Ctrl+Backspace", 0, QApplication::UnicodeUTF8));
        actionTypeset->setText(QApplication::translate("PDFDocument", "Quick Build", 0, QApplication::UnicodeUTF8));
        actionTypeset->setIconText(QApplication::translate("PDFDocument", "Quick Build", 0, QApplication::UnicodeUTF8));
        actionTypeset->setShortcut(QApplication::translate("PDFDocument", "Ctrl+T", "action", QApplication::UnicodeUTF8));
        actionExternalViewer->setText(QApplication::translate("PDFDocument", "External Viewer", 0, QApplication::UnicodeUTF8));
        actionExternalViewer->setIconText(QApplication::translate("PDFDocument", "External Viewer", 0, QApplication::UnicodeUTF8));
        actionPreferences->setText(QApplication::translate("PDFDocument", "&Configure TeXstudio", 0, QApplication::UnicodeUTF8));
        actionStack->setText(QApplication::translate("PDFDocument", "Stac&k", 0, QApplication::UnicodeUTF8));
        actionTile->setText(QApplication::translate("PDFDocument", "&Tile", 0, QApplication::UnicodeUTF8));
        actionGo_to_Source->setText(QApplication::translate("PDFDocument", "&Go to Source", 0, QApplication::UnicodeUTF8));
        actionGo_to_Source->setShortcut(QApplication::translate("PDFDocument", "Ctrl+'", 0, QApplication::UnicodeUTF8));
        actionNew_from_Template->setText(QApplication::translate("PDFDocument", "New from Template...", 0, QApplication::UnicodeUTF8));
        actionNew_from_Template->setShortcut(QApplication::translate("PDFDocument", "Ctrl+Shift+N", 0, QApplication::UnicodeUTF8));
        actionFull_Screen->setText(QApplication::translate("PDFDocument", "Full &Screen", 0, QApplication::UnicodeUTF8));
        actionFull_Screen->setShortcut(QApplication::translate("PDFDocument", "Ctrl+Shift+F", 0, QApplication::UnicodeUTF8));
        actionMagnify->setText(QApplication::translate("PDFDocument", "Magnify", 0, QApplication::UnicodeUTF8));
        actionScroll->setText(QApplication::translate("PDFDocument", "Scroll", 0, QApplication::UnicodeUTF8));
        actionSelect_Text->setText(QApplication::translate("PDFDocument", "Select Text", 0, QApplication::UnicodeUTF8));
        actionSelect_Image->setText(QApplication::translate("PDFDocument", "Select Image", 0, QApplication::UnicodeUTF8));
        actionUserManual->setText(QApplication::translate("PDFDocument", "User &Manual...", 0, QApplication::UnicodeUTF8));
        actionWriteToMailingList->setText(QApplication::translate("PDFDocument", "Email to the mailing list", 0, QApplication::UnicodeUTF8));
        actionSide_by_Side->setText(QApplication::translate("PDFDocument", "&Side by Side", 0, QApplication::UnicodeUTF8));
        actionPlace_on_Left->setText(QApplication::translate("PDFDocument", "Place on Left", 0, QApplication::UnicodeUTF8));
        actionPlace_on_Right->setText(QApplication::translate("PDFDocument", "Place on Right", 0, QApplication::UnicodeUTF8));
        actionQuit_TeXworks->setText(QApplication::translate("PDFDocument", "&Quit TeXstudio", 0, QApplication::UnicodeUTF8));
        actionQuit_TeXworks->setShortcut(QApplication::translate("PDFDocument", "Ctrl+Q", 0, QApplication::UnicodeUTF8));
        actionFind->setText(QApplication::translate("PDFDocument", "Find...", 0, QApplication::UnicodeUTF8));
        actionFind->setShortcut(QApplication::translate("PDFDocument", "Ctrl+F", 0, QApplication::UnicodeUTF8));
        actionFind_Again->setText(QApplication::translate("PDFDocument", "Find Again", 0, QApplication::UnicodeUTF8));
        actionFind_Again->setShortcut(QApplication::translate("PDFDocument", "Ctrl+G", 0, QApplication::UnicodeUTF8));
        actionUpdate_Scripts->setText(QApplication::translate("PDFDocument", "Reload Script List", 0, QApplication::UnicodeUTF8));
        actionManage_Scripts->setText(QApplication::translate("PDFDocument", "Manage Scripts", 0, QApplication::UnicodeUTF8));
        actionShow_Scripts_Folder->setText(QApplication::translate("PDFDocument", "Show Scripts Folder", 0, QApplication::UnicodeUTF8));
        actionAbout_Scripts->setText(QApplication::translate("PDFDocument", "About Scripts...", 0, QApplication::UnicodeUTF8));
        actionS->setText(QApplication::translate("PDFDocument", "s", 0, QApplication::UnicodeUTF8));
        actionCloseSomething->setText(QApplication::translate("PDFDocument", "&Close something", 0, QApplication::UnicodeUTF8));
        actionCloseSomething->setShortcut(QApplication::translate("PDFDocument", "Esc", 0, QApplication::UnicodeUTF8));
        actionScrolling_follows_cursor->setText(QApplication::translate("PDFDocument", "Scrolling follows cursor", 0, QApplication::UnicodeUTF8));
        actionCursor_follows_scrolling->setText(QApplication::translate("PDFDocument", "Cursor follows scrolling", 0, QApplication::UnicodeUTF8));
        actionFind_2->setText(QApplication::translate("PDFDocument", "&Find...", 0, QApplication::UnicodeUTF8));
        actionFind_2->setShortcut(QApplication::translate("PDFDocument", "Ctrl+F", 0, QApplication::UnicodeUTF8));
        actionFind_again->setText(QApplication::translate("PDFDocument", "Find &again", 0, QApplication::UnicodeUTF8));
        actionFind_again->setShortcut(QApplication::translate("PDFDocument", "Ctrl+M, F3", 0, QApplication::UnicodeUTF8));
        actionNew_Window->setText(QApplication::translate("PDFDocument", "New Window", 0, QApplication::UnicodeUTF8));
        actionGrid11->setText(QApplication::translate("PDFDocument", "1x1", 0, QApplication::UnicodeUTF8));
        actionGrid21->setText(QApplication::translate("PDFDocument", "2x1", 0, QApplication::UnicodeUTF8));
        actionGrid12->setText(QApplication::translate("PDFDocument", "1x2", 0, QApplication::UnicodeUTF8));
        actionGrid22->setText(QApplication::translate("PDFDocument", "2x2", 0, QApplication::UnicodeUTF8));
        actionGrid23->setText(QApplication::translate("PDFDocument", "2x3", 0, QApplication::UnicodeUTF8));
        actionGrid33->setText(QApplication::translate("PDFDocument", "3x3", 0, QApplication::UnicodeUTF8));
        actionCustom->setText(QApplication::translate("PDFDocument", "Custom...", 0, QApplication::UnicodeUTF8));
        actionSinglePageStep->setText(QApplication::translate("PDFDocument", "Single Page Step", 0, QApplication::UnicodeUTF8));
        actionSynchronize_multiple_views->setText(QApplication::translate("PDFDocument", "Synchronize multiple views", 0, QApplication::UnicodeUTF8));
        actionPresentation->setText(QApplication::translate("PDFDocument", "Presentation", 0, QApplication::UnicodeUTF8));
        actionPresentation->setShortcut(QApplication::translate("PDFDocument", "F5", 0, QApplication::UnicodeUTF8));
        actionContinuous->setText(QApplication::translate("PDFDocument", "&Continuous", 0, QApplication::UnicodeUTF8));
        action_Print->setText(QApplication::translate("PDFDocument", "&Print...", 0, QApplication::UnicodeUTF8));
        action_Print->setShortcut(QApplication::translate("PDFDocument", "Ctrl+P", 0, QApplication::UnicodeUTF8));
        actionFileOpen->setText(QApplication::translate("PDFDocument", "&Open...", 0, QApplication::UnicodeUTF8));
        actionFileOpen->setShortcut(QApplication::translate("PDFDocument", "Ctrl+O", 0, QApplication::UnicodeUTF8));
        actionBack->setText(QApplication::translate("PDFDocument", "Back", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        actionBack->setToolTip(QApplication::translate("PDFDocument", "Previously shown page", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        actionForward->setText(QApplication::translate("PDFDocument", "Forward", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        actionForward->setToolTip(QApplication::translate("PDFDocument", "Next shown page", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        actionToggleEmbedded->setText(QApplication::translate("PDFDocument", "Windowed/Embedded", 0, QApplication::UnicodeUTF8));
        menuHelp->setTitle(QApplication::translate("PDFDocument", "&Help", 0, QApplication::UnicodeUTF8));
        menuFile->setTitle(QApplication::translate("PDFDocument", "&File", 0, QApplication::UnicodeUTF8));
        menuEdit->setTitle(QApplication::translate("PDFDocument", "&Configure", 0, QApplication::UnicodeUTF8));
        menuView->setTitle(QApplication::translate("PDFDocument", "&View", 0, QApplication::UnicodeUTF8));
        menuGrid->setTitle(QApplication::translate("PDFDocument", "Grid", 0, QApplication::UnicodeUTF8));
        menuWindow->setTitle(QApplication::translate("PDFDocument", "&Window", 0, QApplication::UnicodeUTF8));
        menuShow->setTitle(QApplication::translate("PDFDocument", "Show", 0, QApplication::UnicodeUTF8));
        menuEdit_2->setTitle(QApplication::translate("PDFDocument", "&Edit", 0, QApplication::UnicodeUTF8));
        toolBar->setWindowTitle(QApplication::translate("PDFDocument", "Toolbar", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class PDFDocument: public Ui_PDFDocument {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PDFDOCUMENT_H
